window.StockUI = (() => {
  const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cur=(n,c='USD',digits=2)=>Number.isFinite(n)?`${AppConfig.currencySymbols[c]||c+' '}${new Intl.NumberFormat('en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(n)}`:'N/A';
  const num=(n,d=1)=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}).format(n):'N/A';
  const compact=(n,c='USD')=>Number.isFinite(n)?`${AppConfig.currencySymbols[c]||c+' '}${Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(n)}`:'N/A';
  const percent=n=>Number.isFinite(n)?`${num(n,1)}%`:'N/A';
  function setView(view){['landing','loadingView','dashboard'].forEach(id=>{const el=$(id);el.classList.toggle('hidden',id!==view);el.classList.toggle('active-view',id===view);if(id==='loadingView')el.classList.toggle('flex',id===view)});window.scrollTo({top:0,behavior:'smooth'});}
  function loading(step){const labels=[['Fetching Income Statement...','Connecting to quote and statement sources',22],['Calculating ROE & ROIC Trends...','Normalizing five years of financial history',53],['Applying Buffett & Lynch Rules...','Scoring quality, growth and valuation signals',82]];const x=labels[Math.min(step,labels.length-1)];$('loadingTitle').textContent=x[0];$('loadingSub').textContent=x[1];$('loadingProgress').style.width=x[2]+'%';}
  function error(message){const el=$('searchError');el.textContent=message;el.classList.remove('hidden');}
  function clearError(){$('searchError').classList.add('hidden');}
  function showDashboard(c,b,l,f){AppState.company=c.company;AppState.calculated=c;AppState.buffett=b;AppState.lynch=l;AppState.flags=f;setView('dashboard');
    const co=c.company,r=c.ratios,m=c.metrics; $('dashTickerTop').textContent=co.ticker;$('dashTitle').innerHTML=`${esc(co.name)} <span class="text-slate-400">Overview</span>`;$('dashSubtitle').textContent=`${co.sector} / ${co.industry} · ${co.exchange||'Exchange not supplied'} · ${co.currency}`;$('dashPrice').textContent=cur(co.price,co.currency);$('dashMarketCap').textContent=`Market cap ${compact(co.marketCap,co.currency)}`;$('updatedAt').textContent=`Updated ${new Date().toLocaleDateString()}`;
    const badge=$('dataBadge');badge.textContent=co.dataMode==='live'?'LIVE / THIRD-PARTY':'Using Simulated/Cached Data';badge.className=`data-badge ${co.dataMode==='live'?'live':''}`;
    const notice=$('dataNotice');notice.textContent=`Source: ${co.source||'unspecified'} · ${co.liveNote||''}`+(co.apiError?` Live request detail: ${co.apiError}`:'');notice.classList.remove('hidden');
    $('companyName').textContent=co.name;$('businessDescription').textContent=co.description;$('tableUnits').textContent=`${co.currency} · compact notation unless stated`; $('companyTags').innerHTML=[co.sector,co.industry,co.exchange||'Market not supplied',`Currency: ${co.currency}`].map(t=>`<span class="tag">${esc(t)}</span>`).join('');
    const metrics=[['PRICE',cur(co.price,co.currency),'Reference market price',null],['MARKET CAP',compact(co.marketCap,co.currency),'Current market value',null],['REVENUE GROWTH',percent(r.yoyRevenue),'Latest fiscal year',r.yoyRevenue],['NET MARGIN',percent(r.netMargin),'Latest fiscal year',r.netMargin],['RETURN ON EQUITY',percent(r.roe),'Latest fiscal year',r.roe],['FCF YIELD',percent(r.fcfYield),'Free cash flow / market cap',r.fcfYield]];
    $('snapshotMetrics').innerHTML=metrics.map(([label,value,sub,x])=>`<article class="metric-card"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-sub ${x==null?'trend-flat':x>=0?'trend-up':'trend-down'}">${sub}</div></article>`).join('');
    const mini=[['Revenue CAGR',percent(m.growth),m.growth>5],['Median ROE',percent(m.avgRoe),m.avgRoe>15],['FCF margin',percent(r.fcfMargin),r.fcfMargin>10],['Interest coverage',Number.isFinite(r.interestCoverage)?`${num(r.interestCoverage,1)}×`:'N/A',r.interestCoverage>5]];
    $('miniScorecard').innerHTML=mini.map(x=>`<div class="score-row"><span>${x[0]}</span><b class="${x[2]?'trend-up':'trend-down'}">${x[1]}</b></div>`).join('');
    renderTable(c);renderRatios(c);renderShares(c);renderBuffett(c,b);renderLynch(l,c);renderFlags(f);renderChart(AppState.chartMode);
  }
  function renderTable(c){const years=c.rows.map(r=>r.year);const defs=[['Revenue','revenue','money'],['Revenue growth','yoyRevenue','pct'],['Gross profit','grossProfit','money'],['Gross margin','grossMargin','pct'],['Operating income','operatingIncome','money'],['Operating margin','operatingMargin','pct'],['Net income','netIncome','money'],['Net margin','netMargin','pct'],['Diluted EPS','eps','currency'],['Total assets','assets','money'],['Shareholders’ equity','equity','money'],['Long-term & short-term debt','debt','money'],['Cash & equivalents','cash','money'],['Current ratio','currentRatio','multiple'],['ROE','roe','pct'],['ROIC (estimated)','roic','pct'],['Operating cash flow','cfo','money'],['Capital expenditure','capex','money'],['Free cash flow','fcf','money'],['CFO / net income','cfoNetIncome','multiple'],['Shares outstanding','shares','shares']];
    const fmt=(v,k)=>k==='money'?compact(v,c.company.currency):k==='pct'?percent(v):k==='currency'?cur(v,c.company.currency):k==='shares'?Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(v||0):k==='multiple'?(Number.isFinite(v)?`${num(v,2)}×`:'N/A'):num(v,2);
    $('financialTable').innerHTML=`<thead><tr><th>METRIC</th>${years.map(y=>`<th>${y}</th>`).join('')}</tr></thead><tbody>${defs.map(([label,key,kind])=>`<tr><th>${label}</th>${c.rows.map((r,i)=>{const v=r[key],prev=i?c.rows[i-1][key]:v,better=['debt','capex'].includes(key)?-1:1,delta=Number.isFinite(v)&&Number.isFinite(prev)?(v-prev)*better:0,cls=i===0?'':delta>Math.abs(prev||0)*.005?'cell-good':delta< -Math.abs(prev||0)*.005?'cell-bad':'';return `<td class="${cls}">${fmt(v,kind)}</td>`}).join('')}</tr>`).join('')}</tbody>`;
  }
  function renderRatios(c){const r=c.ratios, items=[['Current ratio',r.currentRatio,'×'],['Quick ratio',r.quickRatio,'×'],['Debt / equity',r.debtEquity,'×'],['Net debt / EBITDA',r.netDebtEbitda,'×'],['Interest coverage',r.interestCoverage,'×'],['CFO / net income',r.cfoNetIncome,'×'],['FCF margin',r.fcfMargin,'%'],['FCF yield',r.fcfYield,'%'],['CapEx / CFO',r.capexCfo,'%'],['P/E',r.pe,'×'],['PEG',r.peg,'×'],['P/B',r.pb,'×'],['P/S',r.ps,'×'],['EV / EBITDA',r.evEbitda,'×'],['P / FCF',r.pFcf,'×'],['Dividend yield',r.dividendYield,'%'],['Dividend payout',r.dividendPayout,'%'],['Book value / share growth',c.metrics.bvGrowth,'%']];$('ratioGrid').innerHTML=items.map(([l,v,u])=>`<div class="ratio-item"><span>${l}</span><b>${Number.isFinite(v)?`${num(v,2)}${u}`:'N/A'}</b><small class="${v>0?'trend-up':'trend-flat'}">Latest available year</small></div>`).join('');}
  function renderShares(c){const a=c.rows.map(r=>r.shares),min=Math.min(...a),max=Math.max(...a),range=max-min||1;$('sharesView').innerHTML=`<div class="shares-chart">${c.rows.map(r=>`<span class="share-col"><i style="height:${22+((r.shares-min)/range)*58}%"></i>${r.year}</span>`).join('')}</div><div class="share-summary"><span>Start ${Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(a[0])}</span><b class="${c.metrics.shareChange<=0?'trend-up':'trend-down'}">${c.metrics.shareChange<=0?'Buybacks':'Dilution'} ${percent(Math.abs(c.metrics.shareChange))}</b><span>Latest ${Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(a.at(-1))}</span></div>`;}
  function renderBuffett(c,b){$('buffettScoreNum').textContent=b.score;$('buffettVerdict').textContent=b.verdict;$('buffettScore').style.borderColor=b.score>=67?'#72e7b9':b.score>=50?'#e2b454':'#dc7979';$('buffettChecks').innerHTML=b.checks.map(x=>{const state=x.ok===null?'INSUFFICIENT DATA':x.ok?'PASS':'REVIEW';return `<div class="check-row"><span class="check-mark ${x.ok===true?'':'warn'}">${x.ok===true?'✓':x.ok===null?'—':'!'}</span><div class="check-copy"><b>${x.label}</b><small>${x.detail}</small></div><span class="check-status ${x.ok===true?'':'warn'}">${state}</span></div>`}).join('');
    $('ownerEarnings').innerHTML=`<div class="value-callout"><span>Median 5Y free cash flow (proxy for owner earnings)</span><b>${compact(b.ownerEarnings,c.company.currency)}</b></div><div class="mt-4 grid grid-cols-2 gap-3"><div class="ratio-item"><span>Owner earnings / share</span><b>${cur(b.oeps,c.company.currency)}</b></div><div class="ratio-item"><span>CapEx / net income</span><b>${Number.isFinite(c.latest.capex/c.latest.netIncome)?percent(c.latest.capex/c.latest.netIncome*100):'N/A'}</b></div></div><p class="mt-3 text-[10px] leading-5 text-slate-500">Owner earnings are approximated as operating cash flow less capital expenditure. Maintenance and growth CapEx are not separated.</p>`;
    const fair=b.fairValue,price=c.company.price,ratio=Number.isFinite(fair/price)?Math.max(0,Math.min(1,fair/price)):0;$('marginSafety').innerHTML=`<div class="grid grid-cols-2 gap-3"><div class="ratio-item"><span>Illustrative fair value / share</span><b>${cur(fair,c.company.currency)}</b></div><div class="ratio-item"><span>Reference market price</span><b>${cur(price,c.company.currency)}</b></div></div><div class="value-track mt-5"><i style="width:${ratio*100}%"></i><em style="left:100%"></em></div><div class="value-labels"><span>Model value coverage ${percent(ratio*100)}</span><b class="${b.upside>=0?'trend-up':'trend-down'}">${Number.isFinite(b.upside)?`${b.upside>=0?'+':''}${percent(b.upside)} modeled upside`:'N/A'}</b></div><p class="mt-4 text-[10px] leading-5 text-slate-500">Illustrative 10-year discounted owner-earnings model: median FCF, growth capped at 8%, 10% discount rate and 12× terminal multiple. Highly sensitive to assumptions; not a price target.</p>`;}
  function renderLynch(l,c){$('lynchCategory').textContent=l.category;$('lynchRationale').textContent=l.reason;$('lynchOtherTypes').innerHTML=['Slow Growers','Stalwarts','Fast Growers','Cyclicals','Turnarounds','Asset Plays','Unclassified'].map(t=>`<span class="tag" style="${t===l.category?'border-color:rgba(114,231,185,.5);color:#2faa7d':''}">${t}</span>`).join('');const r=c.ratios;const pegText=!Number.isFinite(l.peg)?'N/A':l.peg<.5?'Below 0.5 · inexpensive vs modeled growth':l.peg>1.5?'Above 1.5 · premium to modeled growth':'Between 0.5 and 1.5';const daText=!Number.isFinite(l.divAdjPeg)?'N/A':l.divAdjPeg<.5?'Below 0.5':'Above 0.5';$('lynchMetrics').innerHTML=`<div class="grid grid-cols-2 gap-3"><div class="ratio-item"><span>EPS CAGR</span><b>${percent(l.epsGrowth)}</b></div><div class="ratio-item"><span>P/E</span><b>${Number.isFinite(r.pe)?`${num(r.pe,1)}×`:'N/A'}</b></div><div class="ratio-item"><span>PEG</span><b>${Number.isFinite(l.peg)?num(l.peg,2):'N/A'}</b><small>${pegText}</small></div><div class="ratio-item"><span>Dividend-adjusted PEG*</span><b>${Number.isFinite(l.divAdjPeg)?num(l.divAdjPeg,2):'N/A'}</b><small>${daText}</small></div></div><p class="mt-3 text-[10px] leading-5 text-slate-500">* P/E ÷ (EPS growth + dividend yield), using percentage points.</p>`;$('inventoryCheck').className=l.inventoryAlert?'inventory-bad':'inventory-good';$('inventoryCheck').textContent=l.inventoryAlert?`Inventory growth (${percent(l.inventoryGrowth)}) exceeds sales growth (${percent(l.salesGrowth)}). Investigate potential stock build.`:`No inventory growth warning: inventory ${percent(l.inventoryGrowth)} vs sales ${percent(l.salesGrowth)} in latest year.`;}
  function renderFlags(f){$('greenFlags').innerHTML=f.green.map(x=>`<li>${x}</li>`).join('');$('redFlags').innerHTML=f.red.map(x=>`<li>${x}</li>`).join('');const summary=$('overviewFlagsSummary');if(summary)summary.innerHTML=`<span class="overview-flag-count good">✓ ${f.green.length} Green</span><span class="overview-flag-copy">${esc(f.green[0]||'No green flags identified from available data.')}</span><span class="overview-flag-count risk">! ${f.red.length} Red</span><span class="overview-flag-copy">${esc(f.red[0]||'No red flags identified from available data.')}</span>`;}
  function renderChart(mode){AppState.chartMode=mode;document.querySelectorAll('.chart-chip').forEach(b=>b.classList.toggle('active',b.dataset.chart===mode));const c=AppState.calculated;if(!c||!window.Chart)return;const h=c.history, labels=c.metrics.years, defs={growth:{title:'GROWTH / YEAR OVER YEAR',datasets:[['Revenue growth',h.revenueGrowth,'#72e7b9'],['EPS growth',h.epsGrowth,'#b79aff']]},profitability:{title:'PROFITABILITY / %',datasets:[['Gross margin',h.grossMargin,'#72e7b9'],['Operating margin',h.operatingMargin,'#83a8ff'],['Net margin',h.netMargin,'#c29cff']]},returns:{title:'RETURNS / %',datasets:[['ROE',h.roe,'#72e7b9'],['ROA',h.roa,'#83a8ff'],['ROIC (estimated)',h.roic,'#f0bd70']]},balance:{title:'BALANCE SHEET / CURRENCY',datasets:[['Debt',h.debt,'#e98787'],['Cash',h.cash,'#72e7b9']]},valuation:{title:'REFERENCE P/E / ×',datasets:[['P/E (reference price)',h.pe,'#c29cff']]}}[mode];$('chartTitle').textContent=defs.title;const ctx=$('trendChart').getContext('2d');if(AppState.chart)AppState.chart.destroy();const dark=document.documentElement.classList.contains('dark');AppState.chart=new Chart(ctx,{type:'line',data:{labels,datasets:defs.datasets.map(([label,data,color])=>({label,data,borderColor:color,backgroundColor:color+'22',borderWidth:2,pointRadius:3,pointHoverRadius:5,tension:.32,spanGaps:true,fill:false}))},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom',labels:{color:dark?'#aab5c6':'#667085',usePointStyle:true,boxWidth:7,padding:20,font:{size:10}}},tooltip:{backgroundColor:dark?'#151d2e':'#fff',titleColor:dark?'#f8fafc':'#172033',bodyColor:dark?'#cbd5e1':'#526075',borderColor:'rgba(148,163,184,.2)',borderWidth:1}},scales:{x:{grid:{display:false},ticks:{color:dark?'#7e8aa0':'#8994a6',font:{size:10}}},y:{grid:{color:dark?'rgba(148,163,184,.12)':'rgba(148,163,184,.18)'},ticks:{color:dark?'#7e8aa0':'#8994a6',font:{size:9},callback:v=>mode==='valuation'?`${v}×`:mode==='balance'?Intl.NumberFormat('en-US',{notation:'compact'}).format(v):`${v}%`}}}}});}
  function bindNav(){const tabs=[...document.querySelectorAll('.nav-tab')];const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)tabs.forEach(a=>a.classList.toggle('active',a.hash===`#${visible.target.id}`))},{rootMargin:'-25% 0px -60% 0px',threshold:[0,.2,.6]});document.querySelectorAll('.dash-section').forEach(s=>observer.observe(s));}
  return {setView,loading,error,clearError,showDashboard,renderChart,bindNav,fmt:{cur,num,percent,compact}};
})();
